name: ci workflow
on: push
jobs: 
  build-project:
       runs-on: ubuntu-latest
       steps:
          - name: Git configure
            run: | 
              git config --global user.name "hahlawat" 
              git config --global user.email "happyahlawat108@gmail.com" 
      
          - name: checkout code
            run: git clone https://ahlawat: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@github.com/hahlawat/complex-workflow.git
  
          - name: view checkedout code 
            run: cd complex-workflow/ && ls -a

          - name: create a new file 
            run: cd complex-workflow/ && touch rishab 
        
          - name: Add a new file 
            run: cd complex-workflow/ && git add rishab

          - name: Commit a new file 
            run: cd complex-workflow/ && git commit -m "added new file"

          - name: Push 
            run: cd complex-workflow/ && git push origin main