name: ci workflow
on: 
  workflow_dispatch:
    inputs:
      filename:
        description: 'name of the file you wanna delete'     
        required: true
        default: 'happy'
jobs: 
  build-project:
       runs-on: ubuntu-latest
       steps:
          - name: Git configure
            run: | 
              git config --global user.name "hahlawat" 
              git config --global user.email "happyahlawat108@gmail.com" 
      
          - name: checkout code
            run: git clone https://ahlawat:${{secrets.PAT}}@github.com/hahlawat/complex-workflow.git
  
          - name: view checkedout code 
            run: cd complex-workflow/ && ls -a

          - name: delete a new file 
            run: cd complex-workflow/ && rm ${{github.event.inputs.filename}} 
        
          - name: Add a new file 
            run: cd complex-workflow/ && git rm ${{github.event.inputs.filename}}

          - name: Commit a new file 
            run: cd complex-workflow/ && git commit -m "remove file ${{github.event.inputs.filename}}"

          - name: Push 
            run: cd complex-workflow/ && git push origin main