name: ci workflow
on: push
jobs: 
  build-project:
       runs-on: ubuntu-latest
       steps:
          - name: checkout code
            run: git clone https://github.com/hahlawat/complex-workflow.git

          - name: add a new fle
            run: cd complex-workflow/ && ls

      
          

       