name: Complex

on: push

jobs:
   job1:
      runs-on: ubuntu-latest
      steps:
        - run: date
   job2:
      runs-on: windows-latest
      steps:
         - run: date
   job3:
      runs-on: macos-latest
      steps:
         - run: date 
   job4:
      needs: {ubuntu, windows, macos}
      runs-on: macos-latest
      steps:
         - run: date 
      
